title: Heyoka Enterprises — Lawful Business | Monetary Systems | Consultations
description: Heyoka Enterprises provides advisory services in monetary system design, trust administration, legal framework development, and life coaching.
url: https://heyoka-enterprises.github.io/heyoka-enterprises
theme: jekyll-theme-hacker
